name: PR Title Validator
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  title-validation:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Validate PR Title
        uses: ./
        with:
          pattern: JIRA-\d+.*